//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TOS_Helper.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TOS_Helper.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Banner grid maker.
        /// </summary>
        public static string banner_grid_maker {
            get {
                return ResourceManager.GetString("banner_grid_maker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Block type.
        /// </summary>
        public static string block_type {
            get {
                return ResourceManager.GetString("block_type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bronze.
        /// </summary>
        public static string bronze {
            get {
                return ResourceManager.GetString("bronze", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Center out.
        /// </summary>
        public static string centered {
            get {
                return ResourceManager.GetString("centered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Central banner.
        /// </summary>
        public static string central_banner {
            get {
                return ResourceManager.GetString("central_banner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dimensions.
        /// </summary>
        public static string dimensions {
            get {
                return ResourceManager.GetString("dimensions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bottom up.
        /// </summary>
        public static string down {
            get {
                return ResourceManager.GetString("down", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End.
        /// </summary>
        public static string end {
            get {
                return ResourceManager.GetString("end", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate.
        /// </summary>
        public static string generate {
            get {
                return ResourceManager.GetString("generate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate from.
        /// </summary>
        public static string generate_from {
            get {
                return ResourceManager.GetString("generate_from", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generated Waypoints.
        /// </summary>
        public static string generated_waypoints {
            get {
                return ResourceManager.GetString("generated_waypoints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gold.
        /// </summary>
        public static string gold {
            get {
                return ResourceManager.GetString("gold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grid size.
        /// </summary>
        public static string grid_size {
            get {
                return ResourceManager.GetString("grid_size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Length.
        /// </summary>
        public static string length {
            get {
                return ResourceManager.GetString("length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Levels.
        /// </summary>
        public static string levels {
            get {
                return ResourceManager.GetString("levels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Middle-Earth.
        /// </summary>
        public static string middle_earth {
            get {
                return ResourceManager.GetString("middle_earth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nether.
        /// </summary>
        public static string nether {
            get {
                return ResourceManager.GetString("nether", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overworld.
        /// </summary>
        public static string overworld {
            get {
                return ResourceManager.GetString("overworld", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save as Journeymap waypoint.
        /// </summary>
        public static string save_as_journeymap_waypoint {
            get {
                return ResourceManager.GetString("save_as_journeymap_waypoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Silver.
        /// </summary>
        public static string silver {
            get {
                return ResourceManager.GetString("silver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Top down.
        /// </summary>
        public static string up {
            get {
                return ResourceManager.GetString("up", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Utumno.
        /// </summary>
        public static string utumno {
            get {
                return ResourceManager.GetString("utumno", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waypoint name.
        /// </summary>
        public static string waypoint_name {
            get {
                return ResourceManager.GetString("waypoint_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Width.
        /// </summary>
        public static string width {
            get {
                return ResourceManager.GetString("width", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to X.
        /// </summary>
        public static string x {
            get {
                return ResourceManager.GetString("x", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Y.
        /// </summary>
        public static string y {
            get {
                return ResourceManager.GetString("y", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Z.
        /// </summary>
        public static string z {
            get {
                return ResourceManager.GetString("z", resourceCulture);
            }
        }
    }
}
